export const LAYOUT = {
	SCALE_FACTOR: 2,
	WIDTH: 550,
	MAX_HEIGHT: 1200,

	PADDING: 24,
	AVATAR_SIZE: 48,
	AVATAR_GAP: 12,
	MEDIA_GAP_BOTTOM: 8,
	LINE_HEIGHT: 1.4,
	PARAGRAPH_GAP: 16,

	FONT_SIZE_NAME: 15,
	FONT_SIZE_USERNAME: 15,
	FONT_SIZE_TEXT: 16,
	FONT_SIZE_STATS: 13,

	MEDIA_GAP: 16,
	MEDIA_BORDER_RADIUS: 12,

	CARD_BORDER_RADIUS: 16,
	CARD_PADDING: 16,

	NAME_OFFSET_Y: 18,
	USERNAME_OFFSET_Y: 38,
	TEXT_GAP: 4,
	STATS_HEIGHT: 30,
} as const;
