services:
  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-starlight-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-starlight}
      POSTGRES_DB: ${POSTGRES_DB:-starlight}
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgresql_data: